name: Format MDX Files

on:
  push:
    branches:
      - main # Or the branch Tina bot commits to

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Or your preferred version
      - run: npm install
      - run: node formatFrontmatter.js  # Run the formatting script
      - name: Push changes back to repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Auto-format frontmatter"
          git push https://x-access-token:${GH_PAT}@github.com/alielesawy/barebones-starter.git HEAD:main
